server:
  port: 8083

spring:
  application:
    name: notificaciones
  datasource:
    url: jdbc:h2:mem:notifsdb;MODE=LEGACY;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always

# para ver SQL en logs si lo necesitas:
logging:
  level:
    org.hibernate.SQL: info

app:
  cors:
    allowed-origins: "http://localhost:5173"
