server:
  port: 8082

spring:
  datasource:
    url: jdbc:h2:mem:inventariodb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update   # o create-drop si prefieres limpio en cada arranque
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2
  sql:
    init:
      mode: always       # <- esto ejecuta data.sql al arrancar

management:
  endpoints:
    web:
      exposure:
        include: health,info